### PR TITLE
Update zstd version to 1.5.5

### PR DESCRIPTION
**Pull request by io55555**
Upgrade to the latest zstd release:
https://github.com/facebook/zstd/releases/tag/v1.5.5

### CODE REVIEW

**Comment by tisonkun** [comment]
@io55555 Thanks for picking it up! Could you share the motivation for doing this upgrade? We don't always "keep up-to-date" without a reason.

**Comment by io55555** [comment]
1, Correct a rare corruption bug in high compression mode.
2, Improves decompression speed on Linux (+50%), wildly accelerates compression, doubling speed on large files (~1GB).
3, 5.6x faster compression for small fields (1K).
4, Faster compression at level 5-11 (6.2x-16x).

**Comment by PragmaTwice** [comment]
Refer to https://github.com/facebook/zstd/releases/tag/v1.5.5, it seems the performance improvement is pretty impressive.

So it is ok for me.

**Review by PragmaTwice — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]
Thanks for your explanation! LGTM.

**Review by torwig — APPROVED** [review]

**Comment by tisonkun** [comment]
Merging...

Thank you @io55555!

**Pull request merged**
