### PR TITLE
Fetch dependencies from local archives in x.py

### PR DESCRIPTION
**Pull request by PragmaTwice**

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM. Two comments here:

1. We can use [context manager](https://realpython.com/python-with-statement/) for `LocalArchiveServer` to write RAII alike code in `with` block.
2. Do you have a real-world use case that requires this feature? We should somehow reduce the complexity unless it's necessary.

**Comment by PragmaTwice** [comment]
> Do you have a real-world use case that requires this feature? We should somehow reduce the complexity unless it's necessary.

Some users have complained that they now have difficulty compiling kvrocks without internet connection, although I do not see this as a big problem.

**Comment by tisonkun** [comment]
@PragmaTwice I suggest you involve those users directly here to test the implementation, since such local archive server is a customized syntax to use.

**Comment by tisonkun** [comment]
Also, we have already ghproxy to use. Perhaps it's for company internal repositories?

**Comment by PragmaTwice** [comment]
> @PragmaTwice I suggest you involve those users directly here to test the implementation, since such local archive server is a customized syntax to use.

Good advice, I will follow it.

**Comment by tisonkun** [comment]
Closing for now. I tend to keep the logic simple unless there are real requirements and use cases.

From a technical perspective, we _can_ support many things, but from an engineering perspective, it's always important to reduce complexity (entropy).

**Pull request closed without merging**
