### PR TITLE
Update C++ standard to 17

### PR DESCRIPTION
**Pull request by PragmaTwice**
check #970 for details

### CODE REVIEW

**Comment by tanruixiang** [comment]
I compiled successfully on Macos! Thank you very much for your contribution.❤️

**Review by torwig — APPROVED** [review]
@PragmaTwice Thank you for the description and explanation in the related discussion thread.

**Review by git-hulk — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]
LGTM.

**Review by caipengbo — APPROVED** [review]

**Comment by xiaobiaozhao** [comment]
Can I upgrade rocksdb to 7.x at the same time?

**Comment by caipengbo** [comment]
> Can I upgrade rocksdb to 7.x at the same time?

@xiaobiaozhao I think we can wait and see because `rocksdb7.x` is a lot different than `rocksdb6.x`. I'm not sure what services currently use `rocksdb7.x` for production (maybe we can ask in the rocksdb issue), and there's no immediate requirement for kvrocks to use the new `rocksdb7.x` features.

**Comment by PragmaTwice** [comment]
Thanks all. Merging...

**Pull request merged**
