### PR TITLE
Check if the checkpoint seq is in the WAL boundary before using

### LINKED ISSUE #1319: Instantly a large number of writes may cause the slave to enter an infinite loop of full sync
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

Linux 3.10.0-1160.42.2.el7.x86_64
Kvrocks v2.3.0

### Minimal reproduce step

1. modify config rocksdb.wal_ttl_seconds 10800  // aka 3hour
2. modify config rocksdb.wal_size_limit_mb 51200 // aka 50GiB

Accoding to the checkpoint save/resue logic, we can inspect that share_time = 3600s
```
    // Replicas can share checkpiont to replication if the checkpoint existing
    // time is less half of WAL ttl.
    int64_t can_shared_time = storage->config_->RocksDB.WAL_ttl_seconds / 2;
    if (can_shared_time > 60 * 60) can_shared_time = 60 * 60;
    if (can_shared_time < 10 * 60) can_shared_time = 10 * 60;
    auto now = static_cast<time_t>(Util::GetTimeStamp());
    if (now - storage->GetCheckpointCreateTime() > can_shared_time) {
      LOG(WARNING) << "[storage] Can't use current checkpoint, waiting next checkpoint";
      return Status(Status::NotOK, "Can't use current checkpoint, waiting for next checkpoint");
    }
    LOG(INFO) << "[storage] Use current existing checkpoint";
```

In order to reproduce this bug, we only need to write more than 50GiB of data in a short time, and the WAL log will be rorated. At this time, there will be a hole between MaxLsnInCheckpoint and MinLsnInWAL, which will trigger fullsync. However, due to the shared of checkpoint_ Time is set to 1 hour, so the old checkpoint will be used and sent to slave again Since then, we have fallen into a fullsyn loop until 1 hour elapsed.

### What did you expect to see?

the slave works well

### What did you see instead?

the slave was in an infinite loop of full sync, it cannot work and the master needs to waste a lot of bandwidth to re-synchronize data to slaves.

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
This closes #1319

### CODE REVIEW

**Comment by git-hulk** [comment]
This boundary check looks necessary but I can't reproduce this issue on my side.

**Review by torwig — DISMISSED** [review]
LGTM

**Review by caipengbo — DISMISSED** [review]

**Comment by git-hulk** [comment]
@torwig @caipengbo I extended the sequence limitation to require the checkpoint sequence must be greater or equal to the WAL sequence instead of strictly matching.

```
  if (seq < wal_seq) {
    return {Status::NotOK, fmt::format("checkpoint seq: {} is smaller than the WAL seq: {}", seq, wal_seq)};
  }
```

And I have tested if this check works correctly on my side.

**Review by PragmaTwice — APPROVED** [review]

**Review by caipengbo — APPROVED** [review]

**Review by torwig — APPROVED** [review]

**Comment by git-hulk** [comment]
Thanks all, merging...

**Pull request merged**
