### PR TITLE
Fix SISMEMBER should return 0 when key does not exist

### LINKED ISSUE #1659: SISMEMBER behaviour differs from redis
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

Ubuntu 23.04

kvrocks 2.4 and 2.5

### Minimal reproduce step

`SISMEMBER foo bar` (if `foo` doesn't exist)

### What did you expect to see?

0 (as redis does: https://redis.io/commands/sismember/):

```
127.0.0.1:6379> SISMEMBER foo bar 
(integer) 0
```

### What did you see instead?

```
127.0.0.1:6666> SISMEMBER foo bar 
(error) ERR NotFound: 
```

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by enjoy-binbin**
Because we didn't check for not found, causing SISMEMBER
to return an error instead of 0 when the key doesn't exist:
```
127.0.0.1:6379> SISMEMBER foo bar
(integer) 0

127.0.0.1:6666> SISMEMBER foo bar
(error) ERR NotFound:
```

I also checked smismember and it's ok.
Fixes #1659.

### CODE REVIEW

**Comment by enjoy-binbin** [comment]
since this one is a bit small, i skipped the test. (i can add it if needed)

**Review by torwig — APPROVED** [review]

**Review by PragmaTwice — APPROVED** [review]

**Review by git-hulk — APPROVED** [review]

**Comment by mapleFU** [comment]
Seems cmake ci failed @PragmaTwice , is this a flaky test?

**Comment by PragmaTwice** [comment]
Recorded https://github.com/apache/kvrocks/issues/1662

**Comment by PragmaTwice** [comment]
It is not related to our code, not sure why.

**Review by mapleFU — APPROVED** [review]
It's a bit weird because the interface `IsMember` doesn't gurantee `ret=false` when it's not found ( it's guranteed in implemention). But this look good to me

**Comment by enjoy-binbin** [comment]
> It's a bit weird because the interface IsMember doesn't gurantee ret=false when it's not found ( it's guranteed in implemention). But this look good to me

I also found it but chose not to modify it since MIsMember is the same. (i follow MIsMember)

**Comment by mapleFU** [comment]
Seems that MIsMember will resize an array for that, but it doesn't matter :-)

**Pull request merged**
