### PR TITLE
Maybe fix crash in migration

### LINKED ISSUE #1016: Flaky Test TestSlotMigrateFromSlave
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

```
--- FAIL: TestSlotMigrateFromSlave (2.36s)
    server.go:106: 
        	Error Trace:	/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/server.go:106
        	            				/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/server.go:112
        	            				/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/server.go:101
        	            				/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/slotmigrate_test.go:47
        	            				/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/slotmigrate_test.go:65
        	Error:      	Received unexpected error:
        	            	signal: aborted (core dumped)
        	Test:       	TestSlotMigrateFromSlave
FAIL
```

### Solution

Perhaps we should upload server output on test failures? cc @PragmaTwice 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
This should fix #1016, the WriteBatchHandler didn't initialize the member `type_` before using, so it may become an undefined value.

### CODE REVIEW

**Comment by git-hulk** [comment]
Many thanks for the great core file from #1065, also thanks to folks who spent time to locate this issue. cc @PragmaTwice @mapleFU @torwig @tanruixiang

**Comment by mapleFU** [comment]
LGTM, but why does these unit tests fails in these few days? Maybe we still need to bisect the changes?

**Review by torwig — DISMISSED** [review]
LGTM. In general, it's a good idea to initialize this variable because eventually, it can contain garbage. Even if this fix doesn't stop crashes, it should be applied (in my opinion).

**Review by caipengbo — DISMISSED** [review]

**Comment by git-hulk** [comment]
> LGTM, but why does these unit tests fails in these few days? Maybe we still need to bisect the changes?

I guess it's the stream batch type that needs to parse the key in [replication.cc#L914-L922](https://github.com/apache/incubator-kvrocks/blob/unstable/src/cluster/replication.cc#L914-L922). But it's a bit weird since the logic was added 3 months ago.

**Comment by git-hulk** [comment]
> LGTM. In general, it's a good idea to initialize this variable because eventually, it can contain garbage. Even if this fix doesn't stop crashes, it should be applied (in my opinion).

The CI looks green now

**Comment by git-hulk** [comment]
@torwig I got your point, will append a commit to enhance.

**Comment by torwig** [comment]
@git-hulk You are right, the logic was added 3 months ago, but issues with uninitialized variables or data races could be "hidden/invisible" for a long time. At least, from my experience, data races are very hard to reproduce :)

**Review by PragmaTwice — DISMISSED** [review]

**Review by tisonkun — APPROVED** [review]

**Comment by git-hulk** [comment]
Thanks all, the CI failure disappeared after applying this patch, will merge it first to avoid blocking other PRs.

**Pull request merged**
