### PR TITLE
fix: Add timeouts to go-redis client and ping on client creation

### PR DESCRIPTION
**Pull request by torwig**
This prevents failing tests on MacOS13 here: https://github.com/apache/kvrocks/pull/2324

### CODE REVIEW

**Comment by git-hulk** [comment]
https://github.com/apache/kvrocks/blob/unstable/tests/gocase/tls/tls_test.go#L57 This case would not return the NOAUTH error since it sent the plain command to the TLS port. So it will return the connection closed by peer error.

**Comment by torwig** [comment]
@git-hulk Yes, today I'll try to make some changes to the initial ones.

**Comment by torwig** [comment]
Please, review.

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
> Please, review.

I suggest you can avoid using imperative sentences. It reads rudely.

**Comment by torwig** [comment]
@tisonkun I'm sorry, I didn't want to sound rude or offensive.

**Pull request merged**
