### PR TITLE
Make Status::Code::cOK private to avoid direct access

### PR DESCRIPTION
**Pull request by PragmaTwice**

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]

**Review by git-hulk — APPROVED** [review]

**Comment by PragmaTwice** [comment]
Thanks all. Merging...

**Comment by ShooterIT** [comment]
a taste problem, why use `cOK` instead of `kOK`, for const variables, we use `k` prefix but this one 🙃

**Comment by PragmaTwice** [comment]
> a taste problem, why use `cOK` instead of `kOK`, for const variables, we use `k` prefix but this one 🙃

Maybe you need to ask the author of Status. I just use the original name.

**Comment by git-hulk** [comment]
😭 This should be a typo from me, we copied the status from rocksdb and forgot to remove the `c` prefix.

**Pull request merged**
