### PR TITLE
Build multiple operation system artifacts when releasing the new tag

### PR DESCRIPTION
**Pull request by karelrooted**

### CODE REVIEW

**Comment by git-hulk** [comment]
WoW, I love this PR!

**Review by ShooterIT — APPROVED** [review]
So we can try on macOS

**Comment by karelrooted** [comment]
> So we can try on macOS

mac os artifacts is not being builded in this PR, add on this PR or wait for next PR ?

**Comment by git-hulk** [comment]
yeah, I would submit another PR to support home brew

**Review by git-hulk — APPROVED** [review]

**Pull request merged**
