### PR TITLE
Bump zlib to 1.3.1

### PR DESCRIPTION
**Pull request by aleksraiden**
Update zlib to 1.3.1 release. Full changelog - https://github.com/madler/zlib/releases/tag/v1.3.1

Key features:

- Fix bug in inflateSync() for data held in bit buffer
- Add LIT_MEM define to use more memory for a small deflate speedup
- Fix decision on the emission of Zip64 end records in minizip
- Neutralize zip file traversal attacks in miniunz

### CODE REVIEW

**Review by git-hulk — DISMISSED** [review]

**Comment by mapleFU** [comment]
Will merge if CI success...

**Comment by aleksraiden** [comment]
As I see, something in cmake scripts, need a help in this point

**Comment by aleksraiden** [comment]
A bug are fixed at https://github.com/madler/zlib/commit/f1f503da85d52e56aae11557b4d79a42bcaa2b86

**Comment by mapleFU** [comment]
I'm not so familiar with cmake, maybe @PragmaTwice could help

**Comment by aleksraiden** [comment]
> I'm not so familiar with cmake, maybe @PragmaTwice could help

All OK, maintainer of  a zlib has been fix a bug, so we are waiting next release.

**Comment by aleksraiden** [comment]
Update to latest head, includes all current fix, instead of 1.3.1.

**Comment by tisonkun** [comment]
> A bug are fixed at [madler/zlib@f1f503d](https://github.com/madler/zlib/commit/f1f503da85d52e56aae11557b4d79a42bcaa2b86)

Then let's wait for the next release. We're not urgent to move the zlib version here.

**Pull request closed without merging**
