### PR TITLE
Add some RAII type for evbuffer to avoid manual free

### PR DESCRIPTION
**Pull request by PragmaTwice**
- Remove all manual call to `free` and `evbuffer_free`
- Add RAII type `UniqueEvbufReadln` and `UniqueEvbuf`

### CODE REVIEW

**Comment by PragmaTwice** [comment]
Probably we could switch from cppcheck to clang tidy for static analysis 🤣

**Comment by PragmaTwice** [comment]
Finally fix the cppcheck issue, update cppcheck to 1.90 (in ubuntu 20.04) and add some extra flags.
I disabled `missingInclude` because it is a complex procedure to let cppcheck find all headers since we have not configured the repo by cmake and not generated a compile command database.

**Comment by ShooterIT** [comment]
cool, thanks, don't read yet, but i love this idea.
And i also wanted to implement `fd` guard, but no action.

**Comment by PragmaTwice** [comment]
Clicked wrong button 🤣

**Comment by PragmaTwice** [comment]
And this PR is ready for review now~

**Review by git-hulk — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
