### PR TITLE
Start redis server in go case

### PR DESCRIPTION
**Pull request by ColinChamber**

### CODE REVIEW

**Comment by ColinChamber** [comment]
I've modified [it](https://github.com/apache/incubator-kvrocks/pull/920/files#diff-ee5674d65ebc44b8f0857a4f3c5f47965ca752d5120d9dfa65537bab0150e8fbR165).  Why can't ci find the such [file](https://github.com/apache/incubator-kvrocks/actions/runs/3121382587/jobs/5062648416#step:11:434)?  I need some help.

**Comment by Ranxy** [comment]
This is because the redis build uses cache, and you need to update cache-redis to add redis-server to it 
https://github.com/apache/incubator-kvrocks/blob/unstable/.github/workflows/kvrocks.yaml#L137-L143

**Comment by ColinChamber** [comment]
Thank you for your support @Ranxy

**Comment by ColinChamber** [comment]
It seems that redis-server has been successfully moved to the `$HOME/local/bin/` directory. [Here](https://github.com/apache/incubator-kvrocks/actions/runs/3144465670/jobs/5110553092#step:5:5). But why is it unsuccessful when starting redis-server? [Here](https://github.com/apache/incubator-kvrocks/actions/runs/3144465670/jobs/5110553092#step:11:558). In addition, redis-server has not been compiled successfully in other environments. 
Can you give me some help? Thanks for your time. @git-hulk @PragmaTwice

**Comment by ColinChamber** [comment]
> It seems that redis-server has been successfully moved to the `$HOME/local/bin/` directory. [Here](https://github.com/apache/incubator-kvrocks/actions/runs/3144465670/jobs/5110553092#step:5:5). But why is it unsuccessful when starting redis-server? [Here](https://github.com/apache/incubator-kvrocks/actions/runs/3144465670/jobs/5110553092#step:11:558). In addition, redis-server has not been compiled successfully in other environments. Can you give me some help? Thanks for your time. @git-hulk @PragmaTwice

cc @caipengbo Could you help me?

**Comment by tisonkun** [comment]
@ColinChamber I suggest you write a real-world test case requiring starting a redis server. And I can help you with implementing this functionality.

Currently, I don't see any case needs a Redis server.

**Comment by ColinChamber** [comment]
Sorry for the late reply. #942 This feature needs a Redis server to check if the `dump.rdb` can be loaded correctly. Thanks for your help. @tisonkun

**Comment by ColinChamber** [comment]
#942 This PR is not completed. Only to explain why I need to start redis server. I haven't written the test case about saving rdb in gocase. I'm not sure how to do it properly. @tisonkun

**Comment by tisonkun** [comment]
Closed in favor of https://github.com/tisonkun/incubator-kvrocks/tree/start-redis.

@ColinChamber you can make use of the branch and integrate with #942. I will help with integration when there's a real-world use case. If we don't have such a case, I don't want to merge this functionality alone :)

**Comment by tisonkun** [comment]
For example, start a Redis server with:

```go
// populate with map with your configs
srv := util.StartRedisServer(t, map[string]string{})
```

... and in the workflow file:

```bash
./x.py test go build -redisBinPath=/path/to/redis-server
```

**Comment by tisonkun** [comment]
> I'm not sure how to do it properly.

You should find the way by yourself. Or at least try to write some pseudo code. It makes nonsense to ask others to write code for you if you yourself don't know how to do it.

**Comment by ColinChamber** [comment]
> You should find the way by yourself. Or at least try to write some pseudo code. It makes nonsense to ask others to write code for you if you yourself don't know how to do it.

Thank you. I just wanted to seek some advice in advance. I'm not asking anyone to write code for me. I have coded some python scripts to test this. I will convert to gocase by myself.

**Pull request closed without merging**
