### PR TITLE
Add the 北京软告科技股份有限公司 logo to who uses kvrocks

### PR DESCRIPTION
**Pull request by gaoyuanzong**

### CODE REVIEW

**Comment by ShooterIT** [comment]
thanks @gaoyuanzong using kvrocks, let's make it better

**Comment by gaoyuanzong** [comment]
> thanks @gaoyuanzong use kvrocks, let's make it better

**Comment by ShooterIT** [comment]
why did you close it? want to update something?

**Comment by gaoyuanzong** [comment]
> why did you close it? want to update something?

Sorry for the wrong operation just now. Please reopen it

**Pull request closed without merging**
