### PR TITLE
ci: add Debian environment to CI workflow

### LINKED ISSUE #2417: Add a Debian environment to CI workflow
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

Since we use debian as base image now, we should add a Debian environment to CI workflow:

https://github.com/apache/kvrocks/blob/unstable/.github/workflows/kvrocks.yaml#L423-L428

### Solution

--

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by c8ef**
- resolve: #2417

### CODE REVIEW

**Comment by c8ef** [comment]
It appears that CI is experiencing an SSL certificate issue😥

**Comment by aleksraiden** [comment]
> It appears that CI is experiencing an SSL certificate issue😥

Hmm, I quickly read a CI error. What do you mean about ssl issue?

**Comment by c8ef** [comment]
> > It appears that CI is experiencing an SSL certificate issue😥
> 
> Hmm, I quickly read a CI error. What do you mean about ssl issue?

It failed randomly during the first round of testing, possibly due to a networking issue unrelated to the changes made here.

**Review by git-hulk — APPROVED** [review]

**Comment by c8ef** [comment]
Hi, could someone please take a look at this PR as well?🥰

**Comment by git-hulk** [comment]
@c8ef I will merge this PR if no further in one hour.

**Comment by git-hulk** [comment]
@c8ef Thank you!

**Pull request merged**
