### PR TITLE
fix: Travis CI should report failure if commands fail

### PR DESCRIPTION
**Pull request by PragmaTwice**
Travis CI failed days before due to the missing of `libssl-dev`, after my PR #797. So some nightly images did not push to docker hub successfully.

Sorry for that to all developers and users.

### CODE REVIEW

**Review by git-hulk — DISMISSED** [review]
LGTM

**Review by tisonkun — DISMISSED** [review]
@PragmaTwice please check whether the title change is correct. I suggest we write the solution/expected state on PRs, while the issue/error state on issues.

**Comment by PragmaTwice** [comment]
> @PragmaTwice please check whether the title change is correct. I suggest we write the solution/expected state on PRs, while the issue/error state on issues.

Yeah, and it is more accurate than before. Thanks!

**Comment by PragmaTwice** [comment]
Hi guys, I think it is ready now : )

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
