### PR TITLE
Add the support of the ZRANGESTORE command 

### LINKED ISSUE #1460: Add the support of the ZRANGESTORE command
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

This issue considers to support the [zrangestore](https://redis.io/commands/zrangestore/) command.

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by jihuayu**
closed #1460

In this PR
1. Add the support of the ZRANGESTORE command 
2. change `RangeByLex` function signature,make it return `MemberScores` instand of `Member`

### CODE REVIEW

**Review by git-hulk — APPROVED** [review]
LGTM

**Review by torwig — APPROVED** [review]
LGTM

**Comment by git-hulk** [comment]
Thanks all, merging...

**Comment by git-hulk** [comment]
Hi @jihuayu Thanks for your contribution again.

For the merged new command, you can help to add it to the [supported commands](https://github.com/apache/incubator-kvrocks-website/blob/main/docs/supported-commands.md)

**Pull request merged**
