### PR TITLE
refactor: move VERSION to src/folder #1148

### LINKED ISSUE #1148: Move VERSION file to src folder
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Move `VERSION` file to `src` folder, so that we have a tidy root layout.

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by CNLHC**
This fixes #1148.

### CODE REVIEW

**Comment by CNLHC** [comment]
`x.py` is only invoked from the project root so using relative dir in `x.py` seems to be ok.

**Comment by tisonkun** [comment]
I'd prefer to write `VERSION.txt` instead of `.VERSION`. There's no reason for the VERSION file to be hidden.

@PragmaTwice for https://github.com/apache/incubator-kvrocks/issues/1148#issuecomment-1333696239, I'd say that `version.h.in` is not a typical source file also, but we host all source files and meta source files (that generates source files under `src`). You can think of proto definitions.

**Comment by CNLHC** [comment]
> I'd prefer to write `VERSION.txt` instead of `.VERSION`. There's no reason for the VERSION file to be hidden.
> 
> @PragmaTwice for [#1148 (comment)](https://github.com/apache/incubator-kvrocks/issues/1148#issuecomment-1333696239), I'd say that `version.h.in` is not a typical source file also, but we host all source files and meta source files (that generates source files under `src`). You can think of proto definitions.

I agree with @tisonkun that the `VERSION` should be placed in the `src` because this file does influence the output binary and can be regarded as some kind of source file.

**Review by tisonkun — COMMENTED** [review]
@PragmaTwice Another approach is that we thoroughly remove the `VERSION` file but pass the version by CMake option and default to `999.999.999` :)

**Comment by PragmaTwice** [comment]
> @PragmaTwice Another approach is that we thoroughly remove the `VERSION` file but pass the version by CMake option and default to `999.999.999` :)

It seems hard to do so in a source distribution, while users are required to specify a version number to build.

**Comment by tisonkun** [comment]
> It seems hard to do so in a source distribution, while users are required to specify a version number to build.

Yep..

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
Thanks for your contribution! Merging...

**Pull request merged**
