### PR TITLE
Move TCL test unit/type/incr to Go case

### LINKED ISSUE #815: Move TCL test unit/type/incr to Go case

### PR DESCRIPTION
**Pull request by tanruixiang**
It closes #815

### CODE REVIEW

**Comment by tanruixiang** [comment]
@tisonkun I noticed you were online. Can you open the CI for me?

**Comment by git-hulk** [comment]
@tanruixiang cool, thanks for your contribution.

**Review by git-hulk — DISMISSED** [review]

**Review by tisonkun — CHANGES_REQUESTED** [review]
This is not an identical migration, will submit a patch onto this PR.

**Comment by tisonkun** [comment]
Here's the patch https://github.com/tanruixiang/incubator-kvrocks/pull/1.

**Comment by tanruixiang** [comment]
> Here's the patch [tanruixiang#1](https://github.com/tanruixiang/incubator-kvrocks/pull/1).

thank you very much!!

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
Merging...

**Pull request merged**
