### PR TITLE
Refactor Status to avoid large stack size in happy path

### PR DESCRIPTION
**Pull request by PragmaTwice**
Follow the implementation of Status in RocksDB, google absl, doris and more, we refactor the Status to make it just a pointer (8 instead of 40 for libstdc++ std::string).

For happy path (OK status) with large probability, it benefits the performance.

### CODE REVIEW

**Review by torwig — APPROVED** [review]
LGTM

**Review by git-hulk — APPROVED** [review]

**Comment by tisonkun** [comment]
I remember I review a similar patch before, but I cannot find it now..

Good to merge for this one.

**Comment by torwig** [comment]
@tisonkun Yeah, I also had a strong feeling of déjà vu.

**Comment by PragmaTwice** [comment]
Yeah, I used to submit this patch in #1330, but there is always an ICE in gcc9 during LTO.
It has been workarounded in d13dbfd2c0bab0cdc2bc4b3e8f512041b5173633, so this patch can be merged.

**Comment by tisonkun** [comment]
@PragmaTwice That's it! I browse the first page of closed PRs and don't find it. That said, what a large traffic in the community recently 🤣

**Pull request merged**
