### PR TITLE
Fix transforming stream entry values to lowercase

### LINKED ISSUE #801: key from STREAM are always in lowercase
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

694d5617bcb873db8d107decd7fe297e4588360b

### Minimal reproduce step

- Connect via redis-cli
- XADD TESTSTREAM * myKey message
- Then, XREAD TESTSTREAM 0-0

### What did you expect to see?

I expect to see: {myKey, message}

### What did you see instead?

- We get: { mykey, message }

### Anything Else?

@torwig known this bug and preparing patch

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by torwig**
Many thanks to @aleksraiden for testing Streams before this feature was actually released.

Resolves #801

### CODE REVIEW

**Review by git-hulk — APPROVED** [review]

**Review by PragmaTwice — APPROVED** [review]

**Comment by git-hulk** [comment]
Thanks all, merging...

**Comment by git-hulk** [comment]
@torwig Are you in Kvrocks slack channel?

**Comment by torwig** [comment]
@git-hulk Yes, joined a few minutes ago :)

**Comment by git-hulk** [comment]
> @git-hulk Yes, joined a few minutes ago :)

OK, thanks. Will contact you on slack.

**Pull request merged**
