### PR TITLE
XREAD returns dedicated status if it blocks

### PR DESCRIPTION
**Pull request by torwig**
In order to be consistent with such blocking commands like BLPOP and BRPOP.

### CODE REVIEW

**Review by PragmaTwice — COMMENTED** [review]
LGTM, however, I wonder if there could be some test cases to identify this change (if it is not hard to add).

**Comment by torwig** [comment]
@PragmaTwice No because it worked **correctly** even without this change :) 
In this case, the loop wasn't stopped on `s.Is<Status::BlockingCmd>()` clause. But, according to the code, the actual reply wasn't sent because the `reply` variable remained empty.

**Review by PragmaTwice — APPROVED** [review]
got it.

**Comment by torwig** [comment]
Merging...

**Pull request merged**
