### PR TITLE
Systemd service file update

### PR DESCRIPTION
**Pull request by aleksraiden**
A little bit updates, inspired from redis, nginx and mysql service unit definition.

- KVRocks start requirement network-online instead of simple network policy
- Starting a server only after network are fully up
- Change maximum threads allowed (LimitNPROC) to 4096 
- Add timeout by 300 sec for start/stop service
- Addition security setup with flag NoNewPrivileges

### CODE REVIEW

**Review by torwig — APPROVED** [review]
LGTM

**Review by tisonkun — APPROVED** [review]
Good to go :)

Thanks for your contribution!

**Comment by tisonkun** [comment]
Random thoughts - such service config can work better if integrated with package manager like AUR (pacman) or Homebrew.

**Review by git-hulk — APPROVED** [review]

**Comment by tisonkun** [comment]
Merging...

**Pull request merged**
