### PR TITLE
Bump rocksdb to 7.8.3

### PR DESCRIPTION
**Pull request by aleksraiden**
Bump rocksdb up to 7.8.3

### CODE REVIEW

**Comment by tisonkun** [comment]
@aleksraiden could you provide some context here? Do you use this version in production environment?

Version bump can bring upstream goods but also potentially cause instability so it's not a solid reason itself.

**Comment by aleksraiden** [comment]
> @aleksraiden could you provide some context here? Do you use this version in production environment?
> 
> Version bump can bring upstream goods but also potentially cause instability so it's not a solid reason itself.

Yes, we use in our project and in our test and redis-bench shows additions ~10% of performance in this version. And, in my mind, importants, a lot of fixes released in this version.

**Review by tisonkun — APPROVED** [review]
Good to go.

Two coins are suggested here:

1. May you list yourself as users on [the users page](https://kvrocks.apache.org/users)
2. May you share the case, especially the performance results on [our blogs](https://kvrocks.apache.org/blog)

Of course, it's voluntary, while other Kvrocks users can benefit from real-world cases and have more confidence in (upgrading to) such changes.

**Review by torwig — APPROVED** [review]

**Review by git-hulk — APPROVED** [review]

**Comment by tisonkun** [comment]
Merging...

**Comment by xiaobiaozhao** [comment]
> > @aleksraiden could you provide some context here? Do you use this version in production environment?
> > Version bump can bring upstream goods but also potentially cause instability so it's not a solid reason itself.
> 
> Yes, we use in our project and in our test and redis-bench shows additions ~10% of performance in this version. And, in my mind, importants, a lot of fixes released in this version.

additions ~10%  base from 7.7.3？

**Pull request merged**
