### PR TITLE
Add lz4 and zstd compression algorithms options support.

### PR DESCRIPTION
**Pull request by WyattJia**

### CODE REVIEW

**Comment by WyattJia** [comment]
I think I should append some documentation about how to install compression libraries.

**Comment by git-hulk** [comment]
Yes, agreed. We should make sure it works after installing depend libraries.

**Comment by ShooterIT** [comment]
And you should also set these flags when compiling rocksdb. It doesn't work now i think

**Comment by WyattJia** [comment]
> And you should also set these flags when compiling rocksdb. It doesn't work now i think

Yep, I'll add documentation, compilation flags and test cases later.

**Comment by git-hulk** [comment]
https://github.com/KvrocksLabs/kvrocks/blob/unstable/build_detect_platform#L127

Maybe it should work since we added the detection, but didn't have a try on my side.

**Comment by WyattJia** [comment]
> https://github.com/KvrocksLabs/kvrocks/blob/unstable/build_detect_platform#L127
> 
> Maybe it should work since we added the detection, but didn't have a try on my side.

Copy that, I'll fill and check the flags.Thanks.

**Comment by git-hulk** [comment]
Thanks for your hard work. @WyattJia

**Pull request closed without merging**
