### PR TITLE
Add fpm packaging to x.py

### PR DESCRIPTION
**Pull request by PragmaTwice**
- add fpm packaging subcommand `./x.py package fpm`
- add type annotations for all functions
- add `--cmake-path` to `./x.py build`
- remove release workflow and `package.sh`

### CODE REVIEW

**Comment by git-hulk** [comment]
@PragmaTwice This PR looks good to me and it becomes cleaner that we replace most scripts with `x.py`, but I'm wondering how we release those binaries after this PR.

**Comment by PragmaTwice** [comment]
I tried to fix the release workflow and upload packages automatically to a draft release in #751. 

@tisonkun suggested that we can directly remove the release workflow and move packaging scripts to x.py.

I do not know whether the release vote process and the  release workflow are compatible, maybe we can have a discussion.

**Comment by git-hulk** [comment]
Thanks @PragmaTwice, sorry that I didn't have a look at the background.

**Review by git-hulk — APPROVED** [review]

**Comment by xiaobiaozhao** [comment]
I think rename x.py to  build.py is better filename for user.

**Comment by PragmaTwice** [comment]
> I think rename x.py to build.py is better filename for user.

Hi @xiaobiaozhao, this script is versatile for not just build, for example it can execute code inspection tools, package source code, generate rpm packages, etc. (and more and more features are being added) So naming it `build.py` may not express this meaning well, you can refer to https://github.com/apache/incubator-kvrocks/pull/725 for details.

**Comment by PragmaTwice** [comment]
Hi @tisonkun, could you take a look at this PR while free?

**Review by tisonkun — APPROVED** [review]
Thanks!

**Pull request merged**
