### PR TITLE
Fix CMake configuration error in snappy

### LINKED ISSUE #792: CMake error building on Fedora 35
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

Unstable branch: fac42b092810f7273385cd57e881c5e4b91e1158
OS: Fedora 35

### Minimal reproduce step

Clone repo.

mkdir build
cd build
cmake ../

### What did you expect to see?

No errors

### What did you see instead?

```
CMake Error at /usr/lib64/cmake/GTest/GTestTargets.cmake:37 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: GTest::gtest;GTest::gtest_main

  Targets not yet defined: GTest::gmock;GTest::gmock_main

Call Stack (most recent call first):
  /usr/lib64/cmake/GTest/GTestConfig.cmake:42 (include)
  /usr/share/cmake/Modules/FindGTest.cmake:187 (find_package)
  build/_deps/snappy-src/CMakeLists.txt:40 (find_package)
```

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by PragmaTwice**
This closes #792.

### CODE REVIEW

**Comment by PragmaTwice** [comment]
@torwig @aleksraiden Hi, could you guys help me to check whether this PR really fixed the CMake error on Fedora or Debian? So thanks!

Here is a simple script for reference to check it:
```sh
git clone -b fix-792 https://github.com/PragmaTwice/incubator-kvrocks
cd incubator-kvrocks && ./x.py build
```

**Review by tisonkun — COMMENTED** [review]
May you describe a bit how adding these two files helps resolve the issue?

I think it's about CMake resolving order while it looks like we always set `GFLAGS_FOUND` & `GTEST_FOUND` to `false`.

**Comment by PragmaTwice** [comment]
> May you describe a bit how adding these two files helps resolve the issue?
> 
> I think it's about CMake resolving order while it looks like we always set `GFLAGS_FOUND` & `GTEST_FOUND` to `false`.

By default, for `find_package(X)`, CMake will use the builtin `FindX.cmake` file (provided by CMake) to find the X package.
It will try to find the package in system, e.g. packages installed from package manager.
We overwrite this file to make sure CMake does not use some builtin logic to find the package, because we do not need these package in snappy.

It is actually a bug in (old version of) snappy, we defined `SNAPPY_BUILD_TESTS=OFF`, but snappy will always find gtest regardless of our provided option, and we do not need gtest in snappy since we do not build unit tests of snappy.

@tisonkun

**Review by tisonkun — APPROVED** [review]
Thanks for your explanation! Sounds good to me.

Although, I don't have a Fedora env to verify it :P

**Comment by torwig** [comment]
@tisonkun I can confirm that the build process goes smoothly on Fedora 35 now.

**Comment by tisonkun** [comment]
@torwig Thanks for your confirmation!

Merging...

**Comment by aleksraiden** [comment]
@tisonkun I can confirm too, that the build process on Debian 11 are OK.

**Pull request merged**
