### PR TITLE
Fix DECRBY LLONG_MIN caused an overflow

### PR DESCRIPTION
**Pull request by enjoy-binbin**
Note that this may break compatibility since in the past
doing: `DECRBY key -9223372036854775808` would succeed
but create an invalid result. And now we will return an
error rejecting the request.

Before:
```
127.0.0.1:6666> set key 0
OK
127.0.0.1:6666> decrby key -9223372036854775807
(integer) 9223372036854775807
127.0.0.1:6666> get key
"9223372036854775807"

127.0.0.1:6666> set key 0
OK
127.0.0.1:6666> decrby key -9223372036854775808
(integer) -9223372036854775808
127.0.0.1:6666> get key
"-9223372036854775808"
```

After:
```
127.0.0.1:6666> decrby key -9223372036854775808
(error) ERR decrement would overflow
```

### CODE REVIEW

**Review by caipengbo — DISMISSED** [review]

**Comment by git-hulk** [comment]
Hi @enjoy-binbin, thanks for taking care of this. Maybe we should fix it in https://github.com/apache/kvrocks/blob/unstable/src/types/redis_string.cc#L320

**Comment by tisonkun** [comment]
@enjoy-binbin Out of curiosity, do you have a fuzzer to test out Kvrocks? Your recent great fixes seem like a combo rather than random findings :D

**Comment by enjoy-binbin** [comment]
They were actually random findings.
I may be sensitive to this, doing code review and found them (also based on my familiarity with redis)

**Comment by enjoy-binbin** [comment]
@git-hulk when doing the -1 * increment_, the overflow is happended, so i can not do the check
```
    auto s = string_db.IncrBy(args_[1], -1 * increment_, &ret);
```

**Comment by tisonkun** [comment]
> They were actually random findings.

Haha, cool!

**Comment by git-hulk** [comment]
> @git-hulk when doing the -1 * increment_, the overflow is happended, so i can not do the check
> 
> ```
>     auto s = string_db.IncrBy(args_[1], -1 * increment_, &ret);
> ```

Got it, thanks

**Review by git-hulk — APPROVED** [review]

**Review by caipengbo — APPROVED** [review]

**Comment by git-hulk** [comment]
Thanks all, merging...

**Pull request merged**
