### PR TITLE
Use append action instead of nargs for cmake defs in x.py

### PR DESCRIPTION
**Pull request by PragmaTwice**
Currently, we use `nargs=*` for parsing `-D` arguments, e.g. `-D X=1 Y=2` -> `["X=1", "Y=2"]`, `-D X=1 -D Y=2` -> `["Y=2"]`.

We need to change it to `action=append` to align the behavior with CMake, e.g. `-D X=1 -D Y=2` -> `["X=1", "Y=2"]`.

It solved #1254 and fix all wrong argument parsing in GitHub Actions.

### CODE REVIEW

**Review by git-hulk — DISMISSED** [review]

**Review by tisonkun — DISMISSED** [review]
LGTM. May I ask the `disk_stats` related changes? We'd better avoid mixing changes, or at least describe what it is.

**Comment by PragmaTwice** [comment]
> LGTM. May I ask the `disk_stats` related changes? We'd better avoid mixing changes, or at least describe what it is.

Previously, all ASan and TSan checks in CI have never been applied (only the last `-D` was kept, all other cmake defs were ignored), so I try to solve all ASan and TSan reports to make the CI pass.

**Comment by tisonkun** [comment]
Thanks for your explanation! That's reasonable.

**Review by git-hulk — APPROVED** [review]

**Comment by PragmaTwice** [comment]
Thanks all. Merging...

**Pull request merged**
