### PR TITLE
Apply Apache License header for source code 

### LINKED ISSUE #542: [NEW] Apply Apache License header for source code
... and add a CI task to guard the situation.

This is a requirement for Apache release.

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #542.

### CODE REVIEW

**Review by git-hulk — APPROVED** [review]
LGTM

There are still some integration tests(*.tcl) from Redis, need to check whether it's ok to add license header on those files.

**Review by Hexiaoqiao — APPROVED** [review]
LGTM. +1.

**Review by ShooterIT — APPROVED** [review]

**Comment by tisonkun** [comment]
> There are still some integration tests(*.tcl) from Redis, need to check whether it's ok to add license header on those files.

@git-hulk You're right. I'm unfamiliar with those cases so that leave them as is. You can give it a try or I will do in days.

**Comment by git-hulk** [comment]
>

**Comment by git-hulk** [comment]
> @git-hulk You're right. I'm unfamiliar with those cases so that leave them as is. You can give it a try or I will do in days.

okay, thanks @tisonkun.

**Pull request merged**
