### PR TITLE
Fix log-dir and backup-dir appear at the same time.

### LINKED ISSUE #1059: When log-dir and backup-dir appear at the same time, log-dir does not take effect
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

unstable branch.
This bug was introduced on October 24.
https://github.com/apache/incubator-kvrocks/blob/684bcc6ce7060ab507627b8299b8326e9ffbf133/src/config/config.cc#L357-L359

### Minimal reproduce step

There are two ways to reproduce

1. Using the command flags
./kvrocks --log-dir /data/log --backup-dir /data/backup

2. Use configuration files(kvrocks.conf)
backup-dir /data/kvrocks/backup
log-dir /data/log

### What did you expect to see?

Log appears in /data/log

### What did you see instead?

Log appears in /tmp

### Anything Else?

If backup-dir appears, It will trigger the execution of this line of code.
https://github.com/apache/incubator-kvrocks/blob/684bcc6ce7060ab507627b8299b8326e9ffbf133/src/config/config.cc#L357-L359

Just remove this line and the bug will be fixed.
Or we reinitialize glog,because macro LOG will  initialize a singleton object before setting the log location.

https://github.com/google/glog/blob/05fbc65278db1aa545ca5cb743c31bc717a48d0f/src/logging.cc#L930-L940

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by manchurio**
This closes #1059

### CODE REVIEW

**Comment by git-hulk** [comment]
@manchurio Thanks for your report and PR, I think the root cause is using before the glog dir was specified in config::Load, so it will send logs to the default dir(/tmp), so this fix is not exactly correct.

**Comment by manchurio** [comment]
> @manchurio Thanks for your report and PR, I think the root cause is using before the glog dir was specified in config::Load, so it will send logs to the default dir(/tmp), so this fix is not exactly correct.

@git-hulk Thanks for the explanation, do you have any suggestion?

**Comment by git-hulk** [comment]
@manchurio I think we can simply remove the logging when the previous backup dir was changed. So that we won't use glog before `initGoogleLog` was called. cc @mapleFU

**Comment by manchurio** [comment]
But that doesn't stop others from doing it again.

**Comment by git-hulk** [comment]
> backup dir was changed. So that we won't use glog before `initGoogleLog` was called. cc @mapleFU

> But that doesn't stop others from doing it again.

We avoid this by moving `google::InitGoogleLogging` into initGoogleLog(), so that all logs will be sent to stderr.

**Comment by mapleFU** [comment]
> I think we can simply remove the logging when the previous backup dir was changed. So that we won't use glog before `initGoogleLog` was called.

@git-hulk It's ok, but changing the backup dir may cause some problems, maybe we can logging in `set` command?

**Comment by PragmaTwice** [comment]
We do not need to log the first assignment of backup dir:
```diff
--- if (!previous_backup.empty()) { 
+++ if (srv && !previous_backup.empty()) { 
```

**Comment by git-hulk** [comment]
@manchurio #1061 has fixed this bug and will close this PR, feel free to reopen it if need.

**Pull request closed without merging**
