### PR TITLE
Add redis-benchmark to CI

### PR DESCRIPTION
**Pull request by aleksraiden**
Add redis-benchmark and check it after all test passed. Draft #884

### CODE REVIEW

**Comment by aleksraiden** [comment]
Something wrong in CI-mode, when I try to start default kvrocks server  from x.py

**Comment by aleksraiden** [comment]
@torwig Could you please check my dirty Python and clean-up in? As I think we maybe can add all options from original redis-benchmark into options params to bench stage?

**Comment by tisonkun** [comment]
@aleksraiden I suggest you take a look at how `./x.py test go` implement. From my perspective, these two commands can be very similar.

**Comment by aleksraiden** [comment]
@tisonkun thanks, correct, previously I see how to add new integration test with benchmark, but I'am not so perfect Go-dev )

If a path with bench-integration test in Go is more clear, I think, @torwig can help me in this PR

**Comment by tisonkun** [comment]
@aleksraiden I don't mean you should use Golang here. I mean:

```bash
./x.py bench [BUILD]             -p 6666 -q
#            ^ optional binpath  ^ rest parameters
```

**Comment by tisonkun** [comment]
Closed since I don't think this functionality should go into CI tasks per PR commit.

You may think of making a perf page like https://perf.rust-lang.org/ whose source is open. Or at least running a daily job while trying to post the result instead of bury them into CI output internally.

**Pull request closed without merging**
