### PR TITLE
Add tcl tests about redis-cli

### PR DESCRIPTION
**Pull request by shangxiaoxiong**
Add tcl tests about redis-cli to make sure that redis-cli can work well with kvrocks.

### CODE REVIEW

**Comment by git-hulk** [comment]
cool, it's too heavy to import the Redis repository to install the redis-cli, how about using apt/brew to install on CI steps and required to install the redis-cli if wants to run the tcl tests on local.

**Comment by ShooterIT** [comment]
yes, only installing redis-cli in CI is a good idea.
in default redis tcl tests, you don't include this test, we can test it by `--single`.

PS:
I wanted to say we only do that in CI when i left your desk yesterday 😜, actually, redis is not a dependency for kvrocks

**Comment by git-hulk** [comment]
Thanks hard work from @shangxiaoxiong, I see the last modified, my doubt is yum/brew didn't work? so we need to compile the Redis ourself?

**Comment by shangxiaoxiong** [comment]
Redis with the right version should be installed to ensure that tcl tests pass. I failed on my mac. @git-hulk 
There may be no corresponding installation package in some env.

**Comment by git-hulk** [comment]
@shangxiaoxiong I'm sorry for didn't your point, do you mean the older or newer redis-cli was failed on you side? Can we find out those test cases?

**Comment by shangxiaoxiong** [comment]
Older redis-cli was failed.

**Review by ShooterIT — APPROVED** [review]

**Review by git-hulk — APPROVED** [review]

**Pull request merged**
