### PR TITLE
build: migrate go-redis/redis to redis/go-redis

### PR DESCRIPTION
**Pull request by infdahai**
update the go-redis package to support more redis commands and migrate go-redis packages.

What's changed and what's your intention?
---

1. And more specifically, I want to use bzpop<max|min|null>, <z|s>intercard, zmpop go APIs to write some go-unit tests for supporting the more commands from `zset` or `set` in `kvrocks`. These commands from redis(version >= 6.2) are not  implemented in this project.

2. Due to https://github.com/redis/go-redis/discussions/2560#discussioncomment-5720447, we should use `replace` in `go.mod` or change `"github.com/go-redis/redis/v9"` from import-blocks in go files.
The latter is more similar to https://github.com/contribsys/faktory/commit/4454c4a063a7818a1159f2ca5529db9e6094b135 and I prefer to try this based on https://github.com/golang-jwt/jwt/issues/37#issuecomment-892056084.

### CODE REVIEW

**Review by git-hulk — DISMISSED** [review]

**Review by caipengbo — DISMISSED** [review]

**Review by tisonkun — COMMENTED** [review]
> update the go-redis package to support more redis commands.

What does it mean? What commands do you want to test later? In this patch, it doesn't use new commands, and we're not serving with redis-go.

**Review by torwig — DISMISSED** [review]

**Comment by infdahai** [comment]
@tisonkun I modify the issue.

**Comment by infdahai** [comment]
> What does it mean? What commands do you want to test later? In this patch, it doesn't use new commands, and we're not serving with redis-go.

BTW, mabe we can create a template for pull requests and it increases readability for code reviewers, such as [risingwave pr_template](https://github.com/risingwavelabs/risingwave/blob/main/.github/pull_request_template.md) or [clickhouse pr_template](https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md)(for changelogs).

**Comment by tisonkun** [comment]
> mabe we can create a template for pull requests and it increases readability for code reviewers

You're free to make your suggestion and patch, while I never find a long template help. Patches varies from one another and I tend to trust the author to fill necessary info. Also, the reviewers can give their suggestions.

**Review by tisonkun — APPROVED** [review]

**Review by git-hulk — APPROVED** [review]

**Pull request merged**
