### PR TITLE
Split redis_cmd.cc to multiple files by category

### LINKED ISSUE #1138: Split commands/redis_cmd.cc to multiple source files
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

`redis_cmd.cc` is becoming increasingly large, and it might be more organized to split it into multiple source files (or, translation units) by some sort of classification.

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by PragmaTwice**
It closes #1138.

Current file structure in `src/commands`:
```
├── command_parser.h
├── redis_cmd_bit.cc
├── redis_cmd.cc
├── redis_cmd_cluster.cc
├── redis_cmd_error.h
├── redis_cmd_geo.cc
├── redis_cmd.h
├── redis_cmd_hash.cc
├── redis_cmd_key.cc
├── redis_cmd_list.cc
├── redis_cmd_pubsub.cc
├── redis_cmd_replication.cc
├── redis_cmd_script.cc
├── redis_cmd_server.cc
├── redis_cmd_set.cc
├── redis_cmd_sortedint.cc
├── redis_cmd_stream.cc
├── redis_cmd_string.cc
├── redis_cmd_txn.cc
├── redis_cmd_zset.cc
├── scan_util.h
└── ttl_util.h
```

### CODE REVIEW

**Review by git-hulk — DISMISSED** [review]
LGTM, love this pr.

**Comment by caipengbo** [comment]
Isn't the `redis_cmd_` prefix a bit redundant?

**Comment by PragmaTwice** [comment]
> Isn't the `redis_cmd_` prefix a bit redundant?

I am considering `cmd_*`, since there are other source files in this directory.

**Comment by PragmaTwice** [comment]
Though, the current one is acceptable for me.

**Comment by caipengbo** [comment]
How about dropping the prefix?

**Comment by PragmaTwice** [comment]
> How about dropping the prefix?

I think the prefix can make them more distinguishing than other source files (in this dir) in alphabetical order, e.g.
```
a  (cmd)
b
c  (cmd)
d
e  (cmd)
```
than
```
b
cmd_a
cmd_c
cmd_e
d
```

**Review by caipengbo — DISMISSED** [review]

**Comment by PragmaTwice** [comment]
@caipengbo @hulk I did some rename in cd17abfd6b2bd3219f00e843f7b402e3af6cd510:
```
scan_util.h -> scan_base.h
redis_cmd.{h|cc} -> commander.{h|cc}
redis_cmd_*.{h|cc} -> cmd_*.{h|cc}
redis_cmd_error.h -> error_constants.h
```

**Review by caipengbo — APPROVED** [review]

**Review by torwig — APPROVED** [review]
@PragmaTwice Great job!

**Comment by PragmaTwice** [comment]
Thanks all. Merging...

**Pull request merged**
