### PR TITLE
Report error if CMAKE_OSX_DEPLOYMENT_TARGET is not set on darwin

### LINKED ISSUE #776: Report a failure fast if `CMAKE_OSX_DEPLOYMENT_TARGET` unset on MacOS
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

See also https://github.com/apache/incubator-kvrocks/commit/341a989d75783d8dad76bbd5a4473dd345472337#r80998035.

cc @PragmaTwice @xiaobiaozhao 

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by PragmaTwice**
Fix #776.

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
LGTM. Tested on Apple M1.

Out of curiosity, I notice that I don't set `CMAKE_OSX_DEPLOYMENT_TARGET` but instead `MACOSX_DEPLOYMENT_TARGET` and this patch doesn't cause fatal. But why?

**Comment by PragmaTwice** [comment]
> LGTM. Tested on Apple M1.
> 
> Out of curiosity, I notice that I don't set `CMAKE_OSX_DEPLOYMENT_TARGET` but instead `MACOSX_DEPLOYMENT_TARGET` and this patch doesn't cause fatal. But why?

If `CMAKE_OSX_DEPLOYMENT_TARGET` is not set manually, it will be initialized by the environment variable `MACOSX_DEPLOYMENT_TARGET`. So it is consistent : )

**Comment by PragmaTwice** [comment]
Thanks @tisonkun ! Merging...

**Comment by tisonkun** [comment]
> it will be initialized by the environment variable MACOSX_DEPLOYMENT_TARGET. So it is consistent : )

I don't find related code in our codebase. Is it done automatically by CMake's logic?

**Comment by PragmaTwice** [comment]
> > it will be initialized by the environment variable MACOSX_DEPLOYMENT_TARGET. So it is consistent : )
> 
> I don't find related code in our codebase. Is it done automatically by CMake's logic?

Yup. Refer to https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html .

**Pull request merged**
