### PR TITLE
Update dependency to latest version (lz4, libevent, gtest)

### PR DESCRIPTION
**Pull request by aleksraiden**
Updated dependency to latest stable version with patches. 

- Update lz4  to latest 1.9.4
- Update libevent to latest 2.1.12
- Update gtest to latest release in 1.12.х branch

### CODE REVIEW

**Review by xiaobiaozhao — COMMENTED** [review]
LGTM

**Comment by aleksraiden** [comment]
Thanks @xiaobiaozhao. Please review - @git-hulk @PragmaTwice @tisonkun   @torwig

**Review by git-hulk — APPROVED** [review]
LGTM, thanks @aleksraiden

**Review by PragmaTwice — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]
Thank you! Merging...

**Pull request merged**
