### PR TITLE
Move TCL test integration/slotmigrate to Go case

### LINKED ISSUE #945: Move TCL test integration/slotmigrate to Go case

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #945.

### CODE REVIEW

**Comment by tisonkun** [comment]
```
[TIMEOUT]: clients state report follows.
sock5637433bc850 => (IN PROGRESS) BLPOP with same key multiple times should work (issue #801)
Killing still running Redis server 43573

                   The End

Execution time of different units:

!!! WARNING The following tests failed:

*** [TIMEOUT]: clients state report follows.
$ /usr/bin/tclsh tests/test_helper.tcl --server-path /home/runner/work/incubator-kvrocks/incubator-kvrocks/build/kvrocks --tls --single unit/tls --dont-clean
Traceback (most recent call last):
  File "/home/runner/work/incubator-kvrocks/incubator-kvrocks/./x.py", line 397, in <module>
    args.func(**arg_dict)
  File "/home/runner/work/incubator-kvrocks/incubator-kvrocks/./x.py", line 265, in test_tcl
    run(tclsh, 'tests/test_helper.tcl', '--server-path', str(Path(dir).absolute() / 'kvrocks'), *rest,
  File "/home/runner/work/incubator-kvrocks/incubator-kvrocks/./x.py", line 67, in run
    raise RuntimeError(err)
RuntimeError: 
failed to run: ('/usr/bin/tclsh', 'tests/test_helper.tcl', '--server-path', '/home/runner/work/incubator-kvrocks/incubator-kvrocks/build/kvrocks', '--tls', '--single', 'unit/tls', '--dont-clean')
exit with code: 1
```

It seems that TLS tests on ubuntu platform has consistently failed. PTAL @git-hulk @PragmaTwice

**Comment by tisonkun** [comment]
Weird. I don't think running TLS tests should trigger tests for list.

**Comment by tisonkun** [comment]
It seems like something wrong with `test_helper`.

**Review by git-hulk — APPROVED** [review]
LGTM

**Pull request merged**
