### PR TITLE
Make the semantics of TYPE and SCAN commands consistent with Redis

### LINKED ISSUE #928: TYPE and SCAN commands are inconsistent with Redis
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

Release 2.1.0

### Minimal reproduce step

1. [Type command](https://redis.io/commands/type/) return simple string in redis, but return bulk string in kvrocks.
2. [Scan command](https://redis.io/commands/scan/) can return empty key in redis, but return none in kvrocks.

### What did you expect to see?

These two commands should be consistent with Redis.

```
127.0.0.1:6379> set "" value
OK

127.0.0.1:6379 > TYPE ""
string

127.0.0.1:6379 > scan 0
1) "0"
2) 1) ""
```

### What did you see instead?

The semantics of the Type and Scan commands are inconsistent with redis.

```
127.0.0.1:8888> set "" value
OK

127.0.0.1:8888 > TYPE key
"string"

127.0.0.1:8888 > scan 0
1) "0"
2) 1) (nil)
```

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by caipengbo**
fixed #928

### CODE REVIEW

**Comment by git-hulk** [comment]
@caipengbo Can you add some tests for this fix?

**Comment by caipengbo** [comment]
> @caipengbo Can you add some tests for this fix?

 I'll add test cases as soon as possible.

**Comment by git-hulk** [comment]
> > @caipengbo Can you add some tests for this fix?
> 
> I'll add test cases as soon as possible.

Thanks

**Comment by tisonkun** [comment]
@caipengbo could you add test cases and rebase this patch onto master? I think it's almost good to merge.

**Comment by caipengbo** [comment]
Sorry, I have been delayed by some things. I will do it as soon as possible.

**Review by xiaobiaozhao — APPROVED** [review]

**Comment by tisonkun** [comment]
Closed as conflict and no response for a while.

@caipengbo you're welcome to rebase the patch and add test cases so that we revive this pull request.

**Pull request closed without merging**
