### PR TITLE
Fix change type of `ttl_` to `int64_t` in `commands` to avoid disturbing

### LINKED ISSUE #2248: bug: inappropriate type of `ttl_` of `CommandSet`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

Since db2860d until now.

### Minimal reproduce step

https://github.com/apache/kvrocks/blob/a2380535d5602692f3746783c48ccc7bb05cc58e/src/commands/cmd_string.cc#L307

Here determine whether `ttl_` less than `0`, if so, doing deletion. However, the type of `ttl_` if `uint64_t` which is impossible to less than 0.

https://github.com/apache/kvrocks/blob/a2380535d5602692f3746783c48ccc7bb05cc58e/src/commands/cmd_string.cc#L340

### What did you expect to see?

If `ttl_` less than `0`, doing deletion.

### What did you see instead?

The condition will never be true, thus, deletion will never be done.

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by J0HN50N133**
fix #2248

### CODE REVIEW

**Comment by J0HN50N133** [comment]
@git-hulk I've modified all code with similar problem in #2248

**Review by mapleFU — APPROVED** [review]
@PragmaTwice should we enable some checks for signed-unsigned number casting?

**Review by git-hulk — APPROVED** [review]

**Comment by PragmaTwice** [comment]
@J0HN50N133 Hi, could you revert your changes in `cmd_string.cc`? 

I'll handle it since it's a bit complicated than just changing a type.

Also it makes the CI fail to pass.

**Comment by PragmaTwice** [comment]
> I'll handle it since it's a bit complicated than just changing a type.

See #2250.

**Comment by J0HN50N133** [comment]
> @J0HN50N133 Hi, could you revert your changes in `cmd_string.cc`?
> 
> I'll handle it since it's a bit complicated than just changing a type.
> 
> Also it makes the CI fail to pass.

Ok.

**Comment by PragmaTwice** [comment]
Actually you can keep the PR with your changes (except `cmd_string.cc`), but it's also fine if you don't want to continue : )

Thank you for your contribution.

**Pull request closed without merging**
