### PR TITLE
Fix slave can't execute publish command

### PR DESCRIPTION
**Pull request by karelrooted**

### CODE REVIEW

**Comment by karelrooted** [comment]
do we need a new way to implement pub/sub without rely on wal replication ?   the current solution write to db  cause  wal seq to increase (have some feedback from user that it sometimes cause a fullsync when a redis-sentinel failover is trigged, cause by "publish __sentinel:hello" message in new slave)

**Comment by git-hulk** [comment]
It seems fine that don’t write the WAL when the role was slave. But it would be better to propagate it without writing to WAL.

**Review by git-hulk — APPROVED** [review]

**Review by ShooterIT — APPROVED** [review]

**Comment by ShooterIT** [comment]
I feel ok for current solution. But i have a question, why we persist publish messages？

**Comment by git-hulk** [comment]
We want to use the WAL to help us propagating the publish command like others.

**Comment by karelrooted** [comment]
@Mergifyio backport 1.3

**Comment by karelrooted** [comment]
@Mergifyio backport 2.0

**Pull request merged**
