### PR TITLE
Bump fmtlib to 10.0.0

### PR DESCRIPTION
**Pull request by aleksraiden**
Bump fmtlib to 10.0.0. Full release desc - https://github.com/fmtlib/fmt/releases/tag/10.0.0

In this release:

- New floating-point formatting algorithm and many floating-point relative fix
- Improved C++20 module support
- A lot improvements in date and time functions 
- Many new code formatter
- Fixes on UTF-8 support
- Fix many warnings, build improved

### CODE REVIEW

**Review by git-hulk — DISMISSED** [review]
LGTM, thanks for your contribution.

No worry about the CI failure, it's caused by the GitHub Action incident.

**Review by torwig — DISMISSED** [review]

**Comment by PragmaTwice** [comment]
There seems some compile error while using fmt 10 in CI. Could you try to investigate it? Or you can wait me for some free time to handle it (maybe next week).

**Comment by aleksraiden** [comment]
A lot of thanks @torwig about fix issue

**Review by torwig — APPROVED** [review]
LGTM.

**Comment by git-hulk** [comment]
This test case failure didn't relate to the current PR: https://github.com/apache/incubator-kvrocks/actions/runs/4957567221/jobs/8869740176?pr=1435

I am investigating now, won't block this PR to be merged

**Review by git-hulk — APPROVED** [review]

**Comment by git-hulk** [comment]
@aleksraiden Thanks for your contribution.

**Pull request merged**
