### PR TITLE
Support logging to stderr

### PR DESCRIPTION
**Pull request by ColinChamber**
solve #478

### CODE REVIEW

**Comment by ShooterIT** [comment]
Hi @ColinChamber #478  wishes to put log to stdout instead of stderr.

**Comment by ColinChamber** [comment]
Let's wait for the glog release.google/glog#790 @ShooterIT

**Comment by git-hulk** [comment]
@ColinChamber Can use the RC version

**Comment by ShooterIT** [comment]
OK, i notice new version will be released at April 1🥳

**Comment by ColinChamber** [comment]
[google-glog 0.6.0-rc2](https://github.com/google/glog/releases/tag/v0.6.0-rc2). I need to modify the Makefile and CMakeLists.txt @git-hulk

**Comment by git-hulk** [comment]
why we need to modify those files?

**Comment by ColinChamber** [comment]
The way glog is built has changed.

**Comment by ColinChamber** [comment]
> I need to modify the Makefile and CMakeLists.txt 

Kvrocks Makefile and CMakeLists.txt

**Comment by ShooterIT** [comment]
@ColinChamber glog 0.6 is released, you can push this forward 🥳

**Comment by git-hulk** [comment]
@ColinChamber Do you have time to finish this feature? If no, I can move on.

**Comment by git-hulk** [comment]
Will close this PR since we handled it in the new PR #613, thanks for @ColinChamber efforts.

**Pull request closed without merging**
