### PR TITLE
Fix data race in instant metrics

### LINKED ISSUE #1789: Data race detected when recording metrics
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

https://github.com/apache/kvrocks/actions/runs/6363892540/job/17279898076?pr=1776

### What did you expect to see?

CI passed

### What did you see instead?

CI failed

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
Currently, only the server's cron thread will write the instant metrics
and those metrics are accessed by worker threads. So it may have a data race
between the server's cron and workers.

This closes #1789

### CODE REVIEW

**Comment by PragmaTwice** [comment]
I am not sure if we can just disable these two function in TSAN since maybe we can bear some data race here.

**Comment by git-hulk** [comment]
> I am not sure if we can just disable these two function in TSAN since maybe we can bear some data race here.

Yes, that's a nice solution as well. `GetInstantaneousMetric` only be used in the info command and those values are inside memory, so I guess it'd be good to have a read lock here.

**Comment by PragmaTwice** [comment]
> Yes, that's a nice solution as well. `GetInstantaneousMetric` only be used in the info command and those values are inside memory, so I guess it'd be good to have a read lock here.

It seems TrackInstantaneousMetric is called in a server cron (every 100ms?), so I am wondering if it can downgrade the performance of the cron cycle.

**Comment by git-hulk** [comment]
> > Yes, that's a nice solution as well. `GetInstantaneousMetric` only be used in the info command and those values are inside memory, so I guess it'd be good to have a read lock here.
> 
> It seems TrackInstantaneousMetric is called in a server cron (every 100ms?), so I am wondering if it can downgrade the performance of the cron cycle.

Yes, I feel good about this. How about every second?

**Review by PragmaTwice — APPROVED** [review]

**Review by torwig — APPROVED** [review]
Data race fix LGTM.

**Comment by git-hulk** [comment]
Thanks all, merging...

**Pull request merged**
