### PR TITLE
Fix ZUNION hang in syntax error

### PR DESCRIPTION
**Pull request by enjoy-binbin**
Bug was introduced in #1502, without this return, when syntax
error happen, the code will stuck in the while loop and
result a hang.

### CODE REVIEW

**Review by git-hulk — APPROVED** [review]
LGTM, good catch! 👍

**Comment by enjoy-binbin** [comment]
this could be a security issue if there is a release that includes this command
i see 2.5 RC include it, please make sure patch it

**Comment by git-hulk** [comment]
> this could be a security issue if there is a release that includes this command i see 2.5 RC include it, please make sure patch it

Yes, 2.5.0 is voting now, but I'm not sure if we should cancel the vote. This bug would cause the server to be trapped in the dead loop. cc @tisonkun @torwig @torwig @ShooterIT @ColinChamber

**Review by PragmaTwice — APPROVED** [review]

**Comment by git-hulk** [comment]
Thanks all, merging...

**Pull request merged**
