### PR TITLE
Fix rocksdb can't auto resume after no space error

### PR DESCRIPTION
**Pull request by karelrooted**
Fix can't auto resume after no space error when the no space error is only trigger by db_->Write without any other background action (compact/flush)

### CODE REVIEW

**Comment by karelrooted** [comment]
related rocksdb issue: https://github.com/facebook/rocksdb/issues/8217

**Review by git-hulk — DISMISSED** [review]

**Review by git-hulk — APPROVED** [review]

**Review by ShooterIT — APPROVED** [review]

**Comment by karelrooted** [comment]
@Mergifyio backport 1.3

**Comment by karelrooted** [comment]
@Mergifyio backport 1.3

**Comment by karelrooted** [comment]
@Mergifyio backport 1.3

**Pull request merged**
