### PR TITLE
fix(worker): memory leak when Worker::AddConnection() failed

### PR DESCRIPTION
**Pull request by weim0000**
when new connection on the worker, if AddConnection function return the status is not OK, we need call 'delete conn' before 'return'， avoid memory leak

auto conn = new redis::Connection(bev, this);
s = AddConnection(conn);
if (!s.IsOK()) {
  conn->Close();
  **delete conn;**
  return;
}

### CODE REVIEW

**Comment by torwig** [comment]
@weim0000 Thank you for your contribution. Please, run `./x.py format` to format the code accordingly.

**Review by PragmaTwice — APPROVED** [review]

**Review by PragmaTwice — CHANGES_REQUESTED** [review]
Ahh sorry, I've checked the `Connection::Close()` and it will call `Worker::FreeConnection()` to `delete` itself.

So I think it should not be a problem here. cc @git-hulk  

And thus `delete` after `Close()` will cause a double-free.

**Comment by weim0000** [comment]
> Ahh sorry, I've checked the `Connection::Close()` and it will call `Worker::FreeConnection()` to `delete` itself.
> 
> So I think it should not be a problem here. cc @git-hulk
> 
> And thus `delete` after `Close()` will cause a double-free.

oh, yes, you are right;  It is no problem, I'm sorry, I will close the pr

**Comment by git-hulk** [comment]
Yes, the connection is registered in worker, so need to remove from the worker first and then free the connection.

**Pull request closed without merging**
