### PR TITLE
Forward C compiler to build deps in CMake

### PR DESCRIPTION
**Pull request by PragmaTwice**
In this PR, we make sure that those C dependencies with makefiles or automake is compiled by the compiler specified by `CMAKE_C_COMPILER`.

### CODE REVIEW

**Comment by tisonkun** [comment]
Does this patch fix some issues existing now? BTW as the building logic grow complexity, we may rewrite it with Python or other more structural tools :)

**Comment by PragmaTwice** [comment]
> Does this patch fix some issues existing now? BTW as the building logic grow complexity, we may rewrite it with Python or other more structural tools :)

Not yet, but I think it is a potential risk of not specifying the compiler for building dependencies.

Rewriting `build.sh` in python sounds great.

**Review by tisonkun — APPROVED** [review]
No harm to introduce such options as long as we don't promise backward compatibility on build script. `--gcc` and `--clang` looks like a handy option to me, we cannot grow options in this way too much.

**Review by git-hulk — APPROVED** [review]

**Comment by PragmaTwice** [comment]
Thanks everyone, merging...

**Pull request merged**
