### PR TITLE
Print error when occurring the flaky test in TestBitmap

### LINKED ISSUE #1472: Flaky test  TestBitmap
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

TestBitMap fails in https://github.com/apache/incubator-kvrocks/actions/runs/5070341119/jobs/9105869084?pr=1444

### What did you expect to see?

No error.

### What did you see instead?

```
--- FAIL: TestBitmap (355.95s)
    --- FAIL: TestBitmap/SETBIT/GETBIT/BITCOUNT/BITPOS_boundary_check_(type_bitmap) (22.25s)
        bitmap_test.go:149: 
            	Error Trace:	/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/type/bitmap/bitmap_test.go:149
            	Error:      	Not equal: 
            	            	expected: 4294967295
            	            	actual  : 0
            	Test:       	TestBitmap/SETBIT/GETBIT/BITCOUNT/BITPOS_boundary_check_(type_bitmap)
```

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by infdahai**
close: #1472

### CODE REVIEW

**Comment by torwig** [comment]
@infdahai Do you want to investigate the reason for an error by using 2/3 lines instead of one?

**Comment by infdahai** [comment]
Yeah, we should distinguish between CI timeouts and program logic errors. Is there any brief way?

If there is no good one, we can wrap these calls.

**Comment by torwig** [comment]
Right now I don't know the other way so we can try this one.

**Review by torwig — APPROVED** [review]

**Review by git-hulk — APPROVED** [review]
LGTM

**Pull request merged**
