### PR TITLE
Fix `GET` return no error when key type is not string

### LINKED ISSUE #1969: Using `GET` to get json type key will not return error.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable 

### Minimal reproduce step

Using `GET` to get json type key will not return error.
I writed below test case.

```go
t.Run("GET JSON type key", func(t *testing.T) {
	require.NoError(t, rdb.Do(ctx, "JSON.SET", "a", "$", ` {"x":1,"y":2} `).Err())
	require.EqualValues(t, "\x00{\"x\":1,\"y\":2}", rdb.Get(ctx, "a").Val())
})
```

### What did you expect to see?

test failed

### What did you see instead?

test Passed

### Anything Else?

Maybe is this line problem.https://github.com/apache/kvrocks/blob/unstable/src/types/redis_string.cc#L86
```C++
if (metadata.Type() != kRedisString && metadata.size > 0) {
    return rocksdb::Status::InvalidArgument(kErrMsgWrongType);
  }
```
Why do we need to check `metadata.size > 0`?

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by jihuayu**
fixed #1969

### CODE REVIEW

**Comment by git-hulk** [comment]
@jihuayu Could you add a test case to make sure this issue was resolved?

**Comment by jihuayu** [comment]
@git-hulk No problem, I will add test cases for each type.

**Comment by git-hulk** [comment]
> @git-hulk No problem, I will add test cases for each type.

Thank you!

**Comment by git-hulk** [comment]
@jihuayu This bug should be resolved after https://github.com/apache/kvrocks/pull/1971, but can add test cases to make sure it works well if you like.

**Comment by jihuayu** [comment]
@git-hulk All right, I'm a bit busy these days, I will come back later to solve it.

**Comment by jihuayu** [comment]
Many commands have this kind of constraint (cannot operate on keys of other types), and we may need a universal method to test them.
I will find a better way that covers this issue. 
Close this PR.

**Pull request closed without merging**
