### PR TITLE
Have an UI

### PR DESCRIPTION
**Pull request by Venjy**
Have an UI written with react.

### CODE REVIEW

**Comment by PragmaTwice** [comment]
Hi @Venjy, thanks for your contribution!

While it is glad to have a GUI for operations on kvrocks, we currently have no plan to maintain a web application in this repo (apache/incubator-kvrocks).

I think you can consider to maintain it by your self, extract it from a kvrocks fork as a single web app repo, or maybe contact [KvrocksLabs](https://github.com/KvrocksLabs) for any desire to accept it (mail to dev@kvrocks.apache.org).

**Comment by xiaobiaozhao** [comment]
> 

Please create a discussion before you do development

**Comment by Venjy** [comment]
Sorry for no discussing first, will close this PR for now. If there is a plan to maintain a UI later, I will continue. Before that, I will consider making it as a single repo. Thanks for @PragmaTwice 's suggestion.

**Comment by git-hulk** [comment]
Hi @Venjy

Many thanks for your efforts first, As @PragmaTwice mentioned, you can start a discussion to show or discuss what you do.

**Pull request closed without merging**
