### PR TITLE
Release 2.5.1

### PR DESCRIPTION
**Pull request by git-hulk**
**Highlights:** #1568 may the server crash when passing numkeys is -1 in Lua script, and #1615 is caused by the data race when updating the slots info string in cluster mode. That means it won't affect you if you're not using the Lua script or cluster mode.

## Bug Fixes
- #1568 
- #1567
- #1562 
- #1581 
- #1589 
- #1591 
- #1593
- #1576 
- #1556 
- #1595
- #1602 
- #1604 
- #1609 
- #1605 
- #1615

### CODE REVIEW

**Review by caipengbo — APPROVED** [review]
LGTM

**Comment by PragmaTwice** [comment]
Seems some fixes are missing:
- https://github.com/apache/kvrocks/commit/d839d163284a7cda61127a285587a489d243812e
- https://github.com/apache/kvrocks/commit/53b7e879e395653651680f76e29c9e4a63b72f10

**Review by PragmaTwice — APPROVED** [review]
But generally LGTM.

**Review by mapleFU — APPROVED** [review]

**Review by torwig — APPROVED** [review]

**Review by enjoy-binbin — APPROVED** [review]
i see mosts of the commits are mine LOL

**Comment by git-hulk** [comment]
> Seems some fixes are missing:
> 
> * [d839d16](https://github.com/apache/kvrocks/commit/d839d163284a7cda61127a285587a489d243812e)
> * [53b7e87](https://github.com/apache/kvrocks/commit/53b7e879e395653651680f76e29c9e4a63b72f10)

Yes, I don't bring those two commits since they won't affect users, so maybe we can release them in the next minor release.

**Comment by git-hulk** [comment]
> i see mosts of the commits are mine LOL

I think you're the best bug hunter in our community for sure.

**Comment by PragmaTwice** [comment]
Seems that VERSION.txt is not changed.
You can run `./x.py package ...` to append a new commit.

**Comment by PragmaTwice** [comment]
And I think squash merge is not a good idea for this PR. But I don't know how to change it.

So maybe you can just push these commits rather than merge the PR.

**Comment by git-hulk** [comment]
> Seems that VERSION.txt is not changed. You can run `./x.py package ...` to append a new commit.

Yes, I think we can propose commits and get approved first, then merge them into 2.5 and append the version commit.

**Comment by git-hulk** [comment]
> And I think squash merge is not a good idea for this PR. But I don't know how to change it.
> 
> So maybe you can just push these commits rather than merge the PR.

ummm... Looks like it has no way to enable the rebase button for some special branches only: https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#Git.asf.yamlfeatures-Mergebuttons.

Let me pick those commits and push them to 2.5 first, you guys can help to revise them later.

**Comment by enjoy-binbin** [comment]
in the repo's settings, maybe it is https://github.com/apache/kvrocks/settings
there is a Pull Requests section, we can enable the `Allow merge commits`
then do a plain merge for this PR (release)
also, we can update the top comment to reflect the changes of this version (somewaht similar to release notes)

i think we've done it pretty well before, like https://github.com/apache/kvrocks/pull/468

**Comment by git-hulk** [comment]
@enjoy-binbin The merge/rebase button is controlled by: https://github.com/apache/kvrocks/blob/unstable/.asf.yaml#L32 and it seems no way to open for some branches only.

**Comment by enjoy-binbin** [comment]
ohh, in this way, maybe we can also enable the merge button? i think we can go beyond some PRs.
we can control it (when we are doing merge, usually squash is used, and in some cases we need to keep commits we use merge)
that is, the choice of squash or merge is the responsibility of the person for merging the PR

**Comment by git-hulk** [comment]
Yes, I think we can enable the merge button and the merger should know when to use the merge button.

>i think we've done it pretty well before, like https://github.com/apache/kvrocks/pull/468

I will re-edit the PR summary later.

**Comment by enjoy-binbin** [comment]
i raise a PR to enable the plain merge in #1624, we can move the discussion there

**Comment by enjoy-binbin** [comment]
we need to update the VERSION.txt as well

**Comment by git-hulk** [comment]
> we need to update the VERSION.txt as well

@enjoy-binbin Thanks for your warm reminder. The package source will change and change version and I plan to do it when creating the release tarball. But it's also good to append the version  change now.

**Comment by enjoy-binbin** [comment]
i see the tag we made is v2.5.1, we used to tag it without v. see https://github.com/apache/kvrocks/releases

but in here it is 2.5.1, so https://github.com/apache/kvrocks/releases/tag/2.5.1 is a 404 link
image

**Comment by PragmaTwice** [comment]
I think it is a bug of GitHub. Our release tag is `v2.5.1`, and our release note title is `2.5.1`.

It is not required to be equal. No problem here for ourselves.

**Pull request merged**
