### PR TITLE
Fix wrongly append the ERR prefix in no script error

### LINKED ISSUE #1161: Inconsistent NOSCRIPT error reply in the eval command
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

As mentioned in https://github.com/apache/incubator-kvrocks/issues/485#issuecomment-1145563442, Redis will reply `NOSCRIPT No matching script. Please use EVAL` error, but Kvrocks will append an `ERR` as its prefix. And it will cause a compatible issue in some cases like go-redis will use this error message to determine the next step. 

### Minimal reproduce step

```
redis-cli > evalsha 123 0
```

### What did you expect to see?

got an error `NOSCRIPT No matching script. Please use EVAL`

### What did you see instead?

got an error `ERR NOSCRIPT No matching script. Please use EVAL`

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
This closes #1161

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
Although return `Status::Ok` with a `Redis::Error` payload seems weird, this patch fixes the issue.

+1 for merge.

**Review by tisonkun — APPROVED** [review]
Although return `Status::Ok` with a `Redis::Error` payload seems weird, this patch fixes the issue.

+1 for merge.

**Comment by git-hulk** [comment]
> Although return `Status::Ok` with a `Redis::Error` payload seems weird, this patch fixes the issue.
> 
> +1 for merge.

Yes, we are mixed using the status message and error output in many places. But we can unify them in the next PR if it's confusing.

**Review by PragmaTwice — APPROVED** [review]

**Comment by git-hulk** [comment]
Thanks all, merging...

**Pull request merged**
