### PR TITLE
Switch the default value of log-dir to

### LINKED ISSUE #749: Send logs to stdout/stderr by default
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Currently, we sent logs to the log file and it's non obvious enough when failed to start the server. We can send logs to stdout/stderr which will also make docker users happy.

### Solution

Change the log-dir to `stdout` in the config file

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by git-hulk**
This closes #749

### CODE REVIEW

**Review by caipengbo — APPROVED** [review]

**Review by PragmaTwice — APPROVED** [review]

**Comment by git-hulk** [comment]
Thanks all, merging...

**Comment by tisonkun** [comment]
typo swith -> switch 😆

**Comment by git-hulk** [comment]
@tisonkun good catch, I fixed the commit message before merging.. ahaha

**Comment by tisonkun** [comment]
Good to know XD. I notice this typo when watching your video on https://www.bilibili.com/video/BV1QY4y1A74H. When I saw you clicked "create pull request" with a highlight typo underline, I went here to see if it retains.

**Comment by git-hulk** [comment]
@tisonkun Aha, really meticulous. Very happy that tison can notice this video, I learn many good points from [your video](https://www.bilibili.com/video/BV1w54y1Z7VP?share_source=weixin_web&share_times=1).

**Pull request merged**
