### PR TITLE
Fix the misuse of multi-get API

### PR DESCRIPTION
**Pull request by ColinChamber**
Perhaps the MulitGet interface with seven parameters is more suitable for getting multiple values ​​from the metadata column family at once. The [original interface used](https://github.com/facebook/rocksdb/blob/main/include/rocksdb/db.h#L507) is to get many keys **across column families** consistently. There are more details in the rocksdb source code [comments](https://github.com/facebook/rocksdb/blob/main/include/rocksdb/db.h#L554).

### CODE REVIEW

**Review by git-hulk — APPROVED** [review]
LGTM

**Comment by git-hulk** [comment]
cool, I didn't notice this warning comment indeed. Happy New Year!

**Comment by ColinChamber** [comment]
Happy New Year! Best wishes to the Kvrocks community!

**Review by ShooterIT — APPROVED** [review]

**Comment by git-hulk** [comment]
@ColinChamber Thanks for your contribution again~

**Comment by ShooterIT** [comment]
@git-hulk Otherwise, we also should use `MultiGet` to implement `xxxMGET` commands such as `hmget`

**Comment by git-hulk** [comment]
Yes, forgot this point.

**Comment by git-hulk** [comment]
@ColinChamber would you like to fix the hmget command as well?

**Comment by git-hulk** [comment]
Yes, but I forgot the point why we didn't use the MGet API.

**Pull request merged**
