### PR TITLE
feat: Upgrade rocksdb to v7.7.3

### PR DESCRIPTION
**Pull request by xiaobiaozhao**

### CODE REVIEW

**Comment by tanruixiang** [comment]
I suggest putting the test results and conclusions here or in the issue.

**Comment by xiaobiaozhao** [comment]
> I suggest putting the test results and conclusions here or in the issue.

Here is a simple test report

https://github.com/apache/incubator-kvrocks/discussions/1013#discussioncomment-4005680

**Comment by git-hulk** [comment]
I think we can push forward to upgrading since the RocksDB community has confirmed the bad performance when compacting in 6.x and fixed in 7.5.3. Related issue: https://github.com/facebook/rocksdb/issues/9423

**Review by git-hulk — APPROVED** [review]

**Review by caipengbo — APPROVED** [review]
Good job, LGTM! 
Rocksdb 7.x has some new features that maybe we can add to kvrocks(like blob cache)

**Review by tanruixiang — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]

**Review by torwig — APPROVED** [review]
LGTM.

**Review by PragmaTwice — APPROVED** [review]

**Comment by tisonkun** [comment]
Merged. Thank you!

**Pull request merged**
