### PR TITLE
Fix INFO used_memory_rss_human field name

### PR DESCRIPTION
**Pull request by enjoy-binbin**
The name should be used_memory_rss_human according to
the context and Redis documentation.

### CODE REVIEW

**Comment by enjoy-binbin** [comment]
Not sure if anyone would rely on and use used_memory_human, i am leaning towards no...
it is a potential breaking change

Note our doc also describes it as used_memory_rss_human in https://kvrocks.apache.org/docs/info-sections

**Review by mapleFU — APPROVED** [review]
Maybe jemalloc `stats.resident` or other can be used for `used_memory` and `used_memory_human` ? cc @PragmaTwice

**Review by git-hulk — APPROVED** [review]

**Comment by git-hulk** [comment]
> Not sure if anyone would rely on and use used_memory_human, i am leaning towards no... it is a potential breaking change
> 
> Note our doc also describes it as used_memory_rss_human in https://kvrocks.apache.org/docs/info-sections

It should be fine since used_memory_rss_human is only for human reading.

**Review by PragmaTwice — APPROVED** [review]

**Comment by PragmaTwice** [comment]
Thanks. Merging...

**Pull request merged**
