### PR TITLE
Add ParseFloat and replace stod with it

### PR DESCRIPTION
**Pull request by PragmaTwice**
We add `ParseFloat` to `parse_util.h` and replace most of `std::stod` with this newly added function in this PR.

### CODE REVIEW

**Review by torwig — DISMISSED** [review]
LGTM

**Comment by PragmaTwice** [comment]
I notice that gcc implemented floating-point version `std::from_chars` since 11.1, which is a sad story. It means we cannot use `std::from_chars` because it comes too late and the gcc version is too new for some users. So I will implement it using `strto*` in c std library instead.

**Comment by PragmaTwice** [comment]
> I notice that gcc implemented floating-point version `std::from_chars` since 11.1, which is a sad story. It means we cannot use `std::from_chars` because it comes too late and the gcc version is too new for some users. So I will implement it using `strto*` in c std library instead.

done

**Review by git-hulk — APPROVED** [review]
LGTM

**Comment by PragmaTwice** [comment]
Thanks all. Merging...

**Pull request merged**
