### PR TITLE
Unify server's shorten form, change svr to srv

### PR DESCRIPTION
**Pull request by git-hulk**
Currently, we have two shorten forms for the server variable name,
and it will be better to keep a consistent name.

### CODE REVIEW

**Review by mapleFU — APPROVED** [review]
Have a glance and seems that all modified variables is Server

**Comment by git-hulk** [comment]
> Have a glance and seems that all modified variables is Server

Yes, only changed the variable name of server from `svr` to `srv`.

**Comment by mapleFU** [comment]
(I mean nothing weird is changed, aha )

**Review by tisonkun — APPROVED** [review]
Thank you!

**Pull request merged**
