### PR TITLE
Add missing `return`s in redis_metadata.cc

### LINKED ISSUE #929: Some `return` is missing in redis_metadata.cc
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

Latest commit [73092dc](https://github.com/apache/incubator-kvrocks/commit/73092dc4a5e4f87411133efdcf10b393dd8f9ae9) on Aug 17

### Minimal reproduce step

in redis_metadata.cc

in rocksdb::Status ListMetadata::Decode(const std::string &bytes) 
line 282
   if (input.size() < 12) rocksdb::Status::InvalidArgument(kErrMetadataTooShort);

Should be:
if (input.size() < 12) **return** rocksdb::Status::InvalidArgument(kErrMetadataTooShort);

same error at line 287

### What did you expect to see?

if (input.size() < 12) **return** rocksdb::Status::InvalidArgument(kErrMetadataTooShort);

### What did you see instead?

if (input.size() < 12) rocksdb::Status::InvalidArgument(kErrMetadataTooShort);

### Anything Else?

same issue on line 282 and 287

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by aleksraiden**
Fix missing return Close #929

### CODE REVIEW

**Comment by aleksraiden** [comment]
@torwig please, review

**Review by caipengbo — DISMISSED** [review]

**Comment by torwig** [comment]
@aleksraiden Quick action!

**Comment by aleksraiden** [comment]
Found one missing in streams module too

**Review by torwig — APPROVED** [review]
LGTM

**Review by caipengbo — APPROVED** [review]

**Review by PragmaTwice — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]
LGTM. Merging...

@git-hulk @torwig @PragmaTwice we may lack some test coverage here. It should be a potential follow-up.

**Pull request merged**
